# Generated by Django 2.2.7 on 2019-11-23 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0003_commit_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name': 'Repositório', 'verbose_name_plural': 'Repositórios'},
        ),
    ]
