# Generated by Django 2.2.7 on 2019-11-23 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0004_auto_20191123_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='author',
        ),
    ]
