# Generated by Django 2.2.7 on 2019-11-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0006_auto_20191123_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='url',
            field=models.URLField(default='', max_length=255),
        ),
    ]
