# Generated by Django 2.2.7 on 2019-11-23 02:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0007_auto_20191123_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
