# Generated by Django 2.2.7 on 2019-11-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0010_auto_20191125_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='webhook_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
